global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK'

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'

  routes:
    - match:
        severity: critical
      receiver: 'slack-critical'
      group_wait: 10s
      repeat_interval: 30m

    - match:
        severity: warning
      receiver: 'slack-warning'
      group_wait: 30s
      repeat_interval: 1h

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#alerts'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        footer: 'Contract Management System'
        color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'

  - name: 'slack-critical'
    slack_configs:
      - channel: '#critical-alerts'
        send_resolved: true
        title: 'CRITICAL: {{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        footer: 'Contract Management System'
        color: 'danger'

  - name: 'slack-warning'
    slack_configs:
      - channel: '#warning-alerts'
        send_resolved: true
        title: 'WARNING: {{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        footer: 'Contract Management System'
        color: 'warning'

templates:
  - '/etc/alertmanager/template/*.tmpl' 